# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3

    - name: Install npm dependencies
      run: npm install

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Setup Scala (sbt)
      uses: olafurpg/setup-scala@v10
      with:
        scala-version: '3.5.2'  # Adjust to match your build.sbt
        sbt-version: '1.5.5'    # Adjust according to your project

    - name: Build Scala.js project
      run: sbt fastOptJS   # Use `fullOptJS` for production build

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Build with Vite
      run: npm run build  # This triggers Vite to bundle everything

    - name: Run tests
      run: sbt test
